const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bebo', Object.freeze({
 workSettings:()=>ipcRenderer.invoke('bebo:work:settings'),
 workConfigure:value=>ipcRenderer.invoke('bebo:work:configure',value),
 workFolder:()=>ipcRenderer.invoke('bebo:work:folder'),
 workHistory:()=>ipcRenderer.invoke('bebo:work:history'),
 workClear:()=>ipcRenderer.invoke('bebo:work:clear'),
 onWorkChanged:callback=>{const listener=()=>callback();ipcRenderer.on('bebo:work-changed',listener);return()=>ipcRenderer.removeListener('bebo:work-changed',listener);},
 onWorkSettingsChanged:callback=>{const listener=(_event,value)=>callback(value);ipcRenderer.on('bebo:work-settings-changed',listener);return()=>ipcRenderer.removeListener('bebo:work-settings-changed',listener);},
 usageGet:period=>ipcRenderer.invoke('bebo:usage:get',period),
 usageBilling:()=>ipcRenderer.invoke('bebo:usage:billing'),
 usagePricing:()=>ipcRenderer.invoke('bebo:usage:pricing'),
 onUsageChanged:callback=>{const listener=()=>callback();ipcRenderer.on('bebo:usage-changed',listener);return()=>ipcRenderer.removeListener('bebo:usage-changed',listener);},
 assistantGet:()=>ipcRenderer.invoke('bebo:assistant:get'),
 assistantSet:value=>ipcRenderer.invoke('bebo:assistant:set',value),
 onAssistantChanged:callback=>{const listener=(_event,value)=>callback(value);ipcRenderer.on('bebo:assistant-changed',listener);return()=>ipcRenderer.removeListener('bebo:assistant-changed',listener);},
 transcribe:(bytes,mime,language)=>ipcRenderer.invoke('bebo:transcribe',bytes,mime,language),
 transcriptionStop:()=>ipcRenderer.invoke('bebo:transcribe:stop'),
 voiceOptions:()=>ipcRenderer.invoke('bebo:voice:options'),
 voiceGenerate:(text,voice)=>ipcRenderer.invoke('bebo:voice:generate',text,voice),
 voiceStop:()=>ipcRenderer.invoke('bebo:voice:stop'),
 cursorEnabled:enabled=>ipcRenderer.invoke('bebo:cursor:enabled',enabled),
 cursorPreview:()=>ipcRenderer.invoke('bebo:cursor:preview'),
 taskState:()=>ipcRenderer.invoke('bebo:task:state'),
 answer:(id,text)=>ipcRenderer.invoke('bebo:answer',id,text),
 companionMenu:()=>ipcRenderer.invoke('bebo:companion:menu'),
 companionBubble:open=>ipcRenderer.invoke('bebo:companion:bubble',open),
 effectsGet:()=>ipcRenderer.invoke('bebo:effects:get'),
 effectsSet:patch=>ipcRenderer.invoke('bebo:effects:set',patch),
 onEffectsChanged:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('bebo:effects-changed',listener);return()=>ipcRenderer.removeListener('bebo:effects-changed',listener);},
 onTaskState:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('bebo:task-state',listener);return()=>ipcRenderer.removeListener('bebo:task-state',listener);},
 status:()=>ipcRenderer.invoke('bebo:status'),
 connect:key=>ipcRenderer.invoke('bebo:connect',key),
 forgetKey:()=>ipcRenderer.invoke('bebo:connection:forget'),
 onConnectionChanged:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('bebo:connection-changed',listener);return()=>ipcRenderer.removeListener('bebo:connection-changed',listener);},
 plan:prompt=>ipcRenderer.invoke('bebo:plan',prompt),
 approve:id=>ipcRenderer.invoke('bebo:approve',id),
 stop:()=>ipcRenderer.invoke('bebo:stop'),
 listen:()=>ipcRenderer.invoke('bebo:listen'),
 pet:()=>ipcRenderer.invoke('bebo:pet'),
 dashboard:()=>ipcRenderer.invoke('bebo:dashboard'),
 talk:()=>ipcRenderer.invoke('bebo:talk'),
 onTalk:callback=>{const listener=()=>callback();ipcRenderer.on('bebo:talk',listener);return()=>ipcRenderer.removeListener('bebo:talk',listener);},
 onStopped:callback=>{const listener=()=>callback();ipcRenderer.on('bebo:stopped',listener);return()=>ipcRenderer.removeListener('bebo:stopped',listener);},
 setAvatarState:mood=>ipcRenderer.invoke('bebo:avatar-state',mood),
 getAvatarState:()=>ipcRenderer.invoke('bebo:avatar-state:get'),
 onAvatarState:callback=>{const listener=(_event,mood)=>callback(mood);ipcRenderer.on('bebo:avatar-state:changed',listener);return()=>ipcRenderer.removeListener('bebo:avatar-state:changed',listener);},
 phoneStart:()=>ipcRenderer.invoke('bebo:phone:start'),
 phoneStop:()=>ipcRenderer.invoke('bebo:phone:stop'),
 phoneStatus:()=>ipcRenderer.invoke('bebo:phone:status'),
 phoneRefresh:()=>ipcRenderer.invoke('bebo:phone:refresh'),
 phoneDecide:(id,allow)=>ipcRenderer.invoke('bebo:phone:decide',id,allow),
 phoneRevoke:()=>ipcRenderer.invoke('bebo:phone:revoke'),
 phoneAppearance:value=>ipcRenderer.invoke('bebo:phone:appearance',value),
 onPhoneChanged:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('bebo:phone-changed',listener);return()=>ipcRenderer.removeListener('bebo:phone-changed',listener);},
 onRemoteTask:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('bebo:remote-task',listener);return()=>ipcRenderer.removeListener('bebo:remote-task',listener);},
}));
