"use client";
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MotionConfig } from 'motion/react';
import { Smartphone, ArrowDownLeft, ArrowRight, AudioLines, Check, ChevronRight, CircleHelp, Command, Cpu, ExternalLink, FolderOpen, Home, Keyboard, Mic, Monitor, MousePointer2, Palette, Plus, Send, Settings2, ShieldCheck, Sparkles, Square, WandSparkles, X, Zap, Clock3, Volume2, PanelTop, Moon, Play, Trash2 } from 'lucide-react';
import { DesktopPet } from './components/DesktopPet';
import { QuestionPrompt } from './components/QuestionPrompt';
import { AvatarCompanion, ExpressionStudio } from './components/AvatarCompanion';
import { avatarMoods, getTaskMood, type AvatarMood, type AvatarEnergy } from './avatar-state';
import './styles.css';
import { PhoneSetup } from './phone/PhoneSetup';
import { PhoneController } from './phone/PhoneController';
import type { PhoneBridge, RemoteTask } from './phone/types';
import { useBeboVoice, type VoiceBridge } from './components/useBeboVoice';
import { AssistantSettings, useAssistantPreferences } from './components/AssistantSettings';
import { useHoldToTalk } from './phone/useHoldToTalk';
import { transcribeOnDesktop } from './phone/RecordedSpeech';
import { VoiceSettings, CursorSettings } from './components/VoiceSettings';
import { UsagePage } from './components/UsagePage';
import type { UsageBridge } from './usage-types';
import { ChartNoAxesCombined } from 'lucide-react';
import { WorkSettings } from './components/WorkSettings';
import { WorkActivity } from './components/WorkActivity';
import type { WorkBridge } from './work-types';
import type { ConnectionBridge, ConnectionStatus } from './connection-types';
import { readSaved, savePreference } from './storage';

type Action = { type: 'click'|'double_click'|'type'|'key'|'scroll'|'tool'|'done'|'blocked'|'ask'; x: number; y: number; text: string; reason: string };
type Step = { id: string; action: Action; step: number };
type Entry = { text: string; detail: string; time: string; ok: boolean };
type Bridge = PhoneBridge & VoiceBridge & UsageBridge & WorkBridge & ConnectionBridge & { plan:(prompt:string)=>Promise<Step>; approve:(id:string)=>Promise<Step>; stop:()=>Promise<void>; listen:()=>Promise<string>; pet:()=>Promise<void>; dashboard:()=>Promise<void>; talk:()=>Promise<void>; onTalk:(callback:()=>void)=>(()=>void); onStopped:(callback:()=>void)=>(()=>void); setAvatarState?:(mood:AvatarMood)=>Promise<void>; getAvatarState?:()=>Promise<AvatarMood>; onAvatarState?:(callback:(mood:AvatarMood)=>void)=>(()=>void) };
declare global { interface Window { bebo?: Bridge } }
const starterCommands = [{ title:'Open an app', prompt:'Open Google Chrome', desc:'Your favorites, one word away.', icon: PanelTop, color:'peach' },{title:'Find your flow',prompt:'Open Notepad so I can start a focused writing session',desc:'A little less friction. A little more focus.',icon:Zap,color:'lavender'},{title:'Find a file',prompt:'Open File Explorer and show my Downloads folder',desc:'Less searching, more doing.',icon:FolderOpen,color:'green'}];
const validHistory = (value: unknown) => Array.isArray(value) && value.length <= 50 && value.every(item => item && typeof item.text === 'string' && typeof item.detail === 'string' && typeof item.time === 'string' && typeof item.ok === 'boolean');
const validShortcuts = (value: unknown) => Array.isArray(value) && value.length <= 100 && value.every(item => typeof item === 'string' && item.length <= 500);
const validColor = (value: unknown) => ['ember','orbit','sprout','ink'].includes(value as string);

function App(){
 const [page,setPage]=useState('Home'); const [modal,setModal]=useState<string|null>(null); const [prompt,setPrompt]=useState(''); const [key,setKey]=useState(''); const [connected,setConnected]=useState(false); const [busy,setBusy]=useState(false); const [listening,setListening]=useState(false); const [message,setMessage]=useState(''); const [pending,setPending]=useState<Step|null>(null); const [history,setHistory]=useState<Entry[]>(()=>readSaved('bebo-history',[],validHistory)); const [shortcuts,setShortcuts]=useState<string[]>(()=>readSaved('bebo-shortcuts',['Open Google Chrome','Open my Downloads folder','Open Notepad'],validShortcuts)); const [color,setColor]=useState(()=>readSaved('bebo-avatar-edition','ember',validColor)); const [sound,setSound]=useState(()=>readSaved('bebo-sound',true));
 const modalRef=useRef<HTMLDivElement>(null); const promptRef=useRef<HTMLInputElement>(null); const generation=useRef(0); const busyRef=useRef(false); const speechRef=useRef<any>(null); const listeningRef=useRef(false);
 const lastRemoteResult=useRef('');
 const voice = useBeboVoice(sound); const speaking = voice.phase === 'speaking'; const [acting,setActing]=useState(false); const [hasError,setHasError]=useState(false);
 const [questionExpires,setQuestionExpires]=useState<number|null>(null);
 const [connectionStatus,setConnectionStatus]=useState<ConnectionStatus>({connected:false});
 const [energy,setEnergy]=useState<AvatarEnergy>(()=>readSaved<AvatarEnergy>('bebo-energy','lively',value=>value==='lively'||value==='calm'));
 const {preferences}=useAssistantPreferences();
 const enhanced=!!window.bebo?.transcribe&&preferences.transcription==='gpt-transcribe';
 const desktopSpeech=useHoldToTalk({enabled:enhanced&&connected&&!busy&&!pending?.action.type?.match(/^(ask|click|double_click|type|key|scroll|tool)$/),language:'en-US',transcribe:transcribeOnDesktop,onSend:text=>{listeningRef.current=false;setListening(false);void run(text);},onError:text=>{setMessage(text);setHasError(!!text);},onUnavailable:()=>setMessage('Microphone recording is unavailable. Choose Device recognition in Settings.')});
 useEffect(()=>{if(enhanced)setListening(desktopSpeech.listening||desktopSpeech.finishing);},[enhanced,desktopSpeech.listening,desktopSpeech.finishing]);
 const liveMood=getTaskMood({listening,speaking,busy,acting,pendingType:pending?.action.type,hasError});
 useEffect(()=>{savePreference('bebo-energy',energy);},[energy]);
 useEffect(()=>{void window.bebo?.phoneAppearance?.({color,energy}).catch(()=>{});},[color,energy]);
 useEffect(()=>{let alive=true,received=false;const update=(state:RemoteTask)=>{if(!alive)return;
  if('approvalExpires' in state)setQuestionExpires(state.approvalExpires as number|null);busyRef.current=state.busy;setBusy(state.busy);setActing(state.acting);setPending(state.pending as Step|null);setPrompt(state.prompt);setMessage(state.message);setHasError(state.hasError);setListening(!!state.listening);voice.stop();speechRef.current?.abort();window.speechSynthesis?.cancel();
  if(state.source!=='desktop'&&state.pending&&['done','blocked'].includes(state.pending.action.type)&&lastRemoteResult.current!==state.pending.id){lastRemoteResult.current=state.pending.id;setHistory(h=>[{text:state.prompt,detail:state.pending!.action.reason,ok:state.pending!.action.type==='done',time:new Date().toISOString()},...h].slice(0,50));}
 };const subscribe=window.bebo?.onTaskState||window.bebo?.onRemoteTask;const off=subscribe?.(state=>{received=true;update(state);});void window.bebo?.taskState?.().then(state=>{if(!received)update(state);}).catch(()=>{});return()=>{alive=false;off?.();};},[]);
 useEffect(()=>{void window.bebo?.setAvatarState?.(liveMood).catch(()=>{});},[liveMood]);
 useEffect(()=>window.bebo?.onStopped(()=>{desktopSpeech.cancel();generation.current++;listeningRef.current=false;busyRef.current=false;setBusy(false);setListening(false);setPending(null);setMessage('Task stopped.');voice.stop();setActing(false);setHasError(false);}),[]);
 useEffect(()=>{let alive=true,received=false;const update=(status:ConnectionStatus)=>{if(!alive)return;setConnectionStatus(status);setConnected(status.connected);};const off=window.bebo?.onConnectionChanged?.(status=>{received=true;update(status);});window.bebo?.status().then(status=>{if(!received)update(status);}).catch(()=>{});return()=>{alive=false;off?.();};},[]);
 useEffect(()=>{savePreference('bebo-history',history);},[history]);
 useEffect(()=>{savePreference('bebo-shortcuts',shortcuts);},[shortcuts]);
 useEffect(()=>{savePreference('bebo-avatar-edition',color);},[color]);
 useEffect(()=>{savePreference('bebo-sound',sound);},[sound]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const els=modalRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex="0"]:not([disabled])');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};modalRef.current?.querySelector<HTMLElement>('button,input')?.focus();document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[modal]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();promptRef.current?.focus();}if(e.key==='Escape'){void stop();}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[]);
 useEffect(()=>window.bebo?.onTalk(()=>{void listen();}),[connected,listening,sound]);
 useEffect(()=>{const sync=(e:StorageEvent)=>{if(e.key==='bebo-avatar-edition')setColor(readSaved('bebo-avatar-edition','ember',validColor));if(e.key==='bebo-sound')setSound(readSaved('bebo-sound',true));if(e.key==='bebo-energy')setEnergy(readSaved<AvatarEnergy>('bebo-energy','lively',value=>value==='lively'||value==='calm'));};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
 function log(text:string,detail:string,ok:boolean){setHistory(h=>[{text,detail,ok,time:new Date().toISOString()},...h].slice(0,50));}
 function speak(text:string){void voice.speak(text);}
 async function stop(){desktopSpeech.cancel();listeningRef.current=false;voice.stop();setActing(false);setHasError(false);generation.current++;busyRef.current=false;setBusy(false);setListening(false);setPending(null);speechRef.current?.abort();window.speechSynthesis?.cancel();await window.bebo?.stop();}
 async function run(text=prompt){if(!text.trim()||busyRef.current)return;setPrompt(text);setMessage('');setHasError(false);voice.stop();setActing(false);window.speechSynthesis?.cancel();if(!window.bebo||!connected){setModal('connect');return;} const epoch=++generation.current;busyRef.current=true;setBusy(true);setPending(null);try{const step=await window.bebo.plan(text);if(epoch!==generation.current)return;setPending(step);if(['done','blocked'].includes(step.action.type)){log(text,step.action.reason,step.action.type==='done');speak(step.action.reason);}}catch(e){if(epoch===generation.current){setHasError(true);setMessage(String(e).replace('Error: ',''));log(text,'Could not complete the request',false);}}finally{if(epoch===generation.current){setBusy(false);busyRef.current=false;}}}
 async function approve(){if(!pending||busyRef.current)return;voice.stop();const epoch=generation.current;busyRef.current=true;setBusy(true);setActing(true);setHasError(false);try{const next=await window.bebo!.approve(pending.id);if(epoch!==generation.current)return;setPending(next);if(['done','blocked'].includes(next.action.type)){log(prompt,next.action.reason,next.action.type==='done');speak(next.action.reason);}}catch(e){if(epoch===generation.current){setPending(null);setHasError(true);setMessage(String(e));log(prompt,'Stopped before completion',false);}}finally{if(epoch===generation.current){setBusy(false);busyRef.current=false;}}}
 async function answer(id:string,text:string){if(busyRef.current)return false;voice.stop();const epoch=generation.current;busyRef.current=true;setBusy(true);setActing(false);try{const next=await window.bebo!.answer!(id,text);if(epoch!==generation.current)return false;setPending(next as Step);if(['done','blocked'].includes(next.action.type)){log(prompt,next.action.reason,next.action.type==='done');speak(next.action.reason);}return true;}finally{if(epoch===generation.current){setBusy(false);busyRef.current=false;}}}
 async function listen(){
  if(enhanced){if(!connected){setModal('connect');return;}voice.stop();desktopSpeech.toggle();return;}
  if(busyRef.current||listeningRef.current)return;
  const epoch=++generation.current;const current=()=>epoch===generation.current;
  listeningRef.current=true;voice.stop();setMessage('');setHasError(false);setListening(true);
  const finish=()=>{if(current()){listeningRef.current=false;setListening(false);}};
  const failed=(error:unknown)=>{if(current()){setHasError(true);setMessage(String(error).replace(/^Error: (?:Error invoking remote method '[^']+': Error: )?/,''));finish();}};
  if(window.bebo){try{const text=await window.bebo.listen();if(!current())return;finish();setPrompt(text);if(text)void run(text);}catch(error){failed(error);}return;}
  const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
  if(!Speech){finish();setMessage('Voice input is available in the Windows app. You can type a request below.');return;}
  const recognition=new Speech();speechRef.current=recognition;recognition.lang='en-US';recognition.interimResults=false;
  recognition.onresult=(event:any)=>{if(current()){setPrompt(event.results[0][0].transcript);setMessage('Voice captured. Connect the desktop app to carry out your request.');}};
  recognition.onerror=()=>failed('Microphone unavailable. Check microphone permission, or type your request.');recognition.onend=finish;
  try{recognition.start();}catch{failed('Microphone could not start. Please check microphone permissions.');}
 }

 async function forgetKey(){if(!window.bebo?.forgetKey)return;setBusy(true);try{const status=await window.bebo.forgetKey();setConnectionStatus(status);setConnected(false);setKey('');setMessage('The saved key was removed. Your history, settings and phone registration are unchanged.');}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 async function connect(){if(!window.bebo)return;setBusy(true);setActing(false);setHasError(false);setMessage('');try{const status=await window.bebo.connect(key);setConnected(true);setConnectionStatus(status||{connected:true});setKey('');setModal(null);setMessage('Luna is connected. Your key is encrypted on this Windows account and will be remembered after restart.');}catch(e){setHasError(true);setMessage(String(e));}finally{setBusy(false);}}
 return <MotionConfig reducedMotion="user"><div className="app-shell">{page!=='Home'&&pending?.action.type==='ask'&&<div className="task-help-dock"><QuestionPrompt key={pending.id} step={pending} expires={questionExpires} disabled={busy} onAnswer={answer} onStop={stop}/></div>}
 <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Home');}}><img className="brand-avatar" src="./bebo.svg" alt=""/>bebo<span className="brand-dot">.</span></a><div className="workspace-label">YOUR LITTLE SIDEKICK</div><nav>{[{label:'Home',icon:Home},{label:'Activity',icon:Clock3},{label:'Usage',icon:ChartNoAxesCombined},{label:'Shortcuts',icon:Zap},{label:'Personalize',icon:Palette},{label:'Phone',icon:Smartphone}].map(({label,icon:Icon})=><button key={label} className={page===label?'nav-item active':'nav-item'} onClick={()=>setPage(label)}><Icon size={19}/>{label}{label==='Home'&&<span className="nav-dot"/>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="desktop-note"><span className="tiny-star">✳</span><h3>Better together.</h3><p>A little friend.<br/>A little more possibility.</p><button onClick={()=>window.bebo?window.bebo.pet():setModal('desktop')}>Meet desktop Bebo <ArrowRight size={14}/></button></div><button className="nav-item" onClick={()=>setModal('settings')}><Settings2 size={18}/>Settings</button><button className="nav-item" onClick={()=>setModal('help')}><CircleHelp size={18}/>A little help</button><div className="profile"><div className="avatar">Y</div><div><b>Your space</b><span>Make yourself at home</span></div><span className="online-dot"/></div></div></aside>
 <main><header><div className="breadcrumb">Your space <ChevronRight size={13}/><span>{page}</span></div><div className="header-right"><span className="preview-pill"><span/>{window.bebo?'Desktop app':'Browser preview'}</span><button className="icon-button" aria-label="Settings" onClick={()=>setModal('settings')}><Settings2 size={18}/></button></div></header>
 <div className="page-content"><div className="page-heading"><div><div className="eyebrow">A LITTLE HELP. A LOT OF POSSIBILITY.</div><h1>{page==='Home'?<>Life’s easier with a <span>little Bebo.</span></>:page==='Usage'?<>A little work. <span>A clear view.</span></>:page==='Activity'?<>Small steps. <span>Good things.</span></>:page==='Shortcuts'?<>Your words. <span>A head start.</span></>:page==='Phone'?<>Take a little <span>Bebo with you.</span></>:<>A little more <span>you.</span></>}</h1><p>{page==='Home'?'Your voice. Your laptop. Your new favorite sidekick.':page==='Usage'?'Your tokens, voice minutes, and estimated spending. All in one place.':page==='Activity'?'A clear view of what Bebo has done, and what needs your attention.':page==='Shortcuts'?'Keep your everyday requests a click away.':page==='Phone'?'Your pocket companion. Your desktop, within reach.':"Same helpful friend. A personality that feels like home."}</p></div><span className="hello-doodle">hello, human!<svg width="58" height="36" viewBox="0 0 58 36"><path d="M3 4C33 1 49 10 40 31M32 24l8 9 10-7" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></span></div>
 {page==='Home'?<><div className="home-grid"><section className="companion-card avatar-companion-card"><div className="card-top"><span className="pill"><span className="dot"/>YOUR LITTLE COMPANION</span><button className="icon-button" aria-label="Personalize Bebo" onClick={()=>setPage('Personalize')}><WandSparkles size={18}/></button></div><AvatarCompanion mood={liveMood} color={color} energy={energy} onTalk={listen}/></section>
 <section className="conversation-card"><div className="section-kicker"><AudioLines size={18}/> LET’S DO SOMETHING</div><h2>Just say the word.</h2><p>From “open Chrome” to your next big idea.<br/>Bebo’s ready to lend a little hand.</p><div className="prompt-ideas"><button onClick={()=>{setPrompt('Open Google Chrome');promptRef.current?.focus();}}><span className="chrome-icon"/>“Bebo, open Chrome”<ArrowDownLeft size={14}/></button><button onClick={()=>{setPrompt('Open my Downloads folder');promptRef.current?.focus();}}><FolderOpen size={18}/>“Find my Downloads”<ArrowDownLeft size={14}/></button><button onClick={()=>{setPrompt('Open Notepad so I can write down an idea');promptRef.current?.focus();}}><Sparkles size={18}/>“Let’s make something”<ArrowDownLeft size={14}/></button></div><div className="voice-area"><button className={`voice-button ${listening?'is-listening':''}`} onClick={enhanced?listen:listening?stop:listen} disabled={busy}>{listening?<Square size={22}/>:<Mic size={23}/>}</button><b>{listening?'Listening. Take your time.':'Go on, say hello.'}</b><span>{desktopSpeech.finishing?'Transcribing your words…':listening?(enhanced?'Click again to send':'Click again to stop'):'Click to start a conversation'}</span></div><div className="model-status"><span className="model-icon"><Sparkles size={13}/></span><span>Powered by <b>Luna 6</b></span><button onClick={()=>setModal('connect')}>{connected?'Connected':'Connect'}<ChevronRight size={12}/></button></div></section></div>
 <WorkActivity compact/><form className="command-bar" onSubmit={e=>{e.preventDefault();void run();}}><span className="command-spark"><Sparkles size={19}/></span><input ref={promptRef} aria-label="Ask Bebo" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="What can I help you with?" maxLength={4000}/><kbd>Ctrl K</kbd><button type="submit" className="send-button" disabled={!prompt.trim()||busy} aria-label="Send request">{busy?<span className="loading-spinner"/>:<ArrowRight size={20}/>}</button></form>
 {(message||pending||busy)&&<div className="task-panel" aria-live="polite">{busy&&pending?.action.type!=='ask'?<><span className="loading-spinner"/><b>{message || 'Bebo is choosing the next step…'}</b><button onClick={stop}>Stop</button></>:pending?.action.type==='ask'?<QuestionPrompt key={pending.id} step={pending} expires={questionExpires} disabled={busy} onAnswer={answer} onStop={stop}/>:pending?<><ShieldCheck size={20}/><div><b>{['done','blocked'].includes(pending.action.type)?'Bebo’s result':`Step ${pending.step} · ${pending.action.type.replace('_',' ')}`}</b><p>{pending.action.reason}</p>{['type','tool'].includes(pending.action.type)&&<code>{pending.action.text}</code>}{pending.action.type==='key'&&<code>{pending.action.text}</code>}{['click','double_click','scroll'].includes(pending.action.type)&&<code>Position: {pending.action.x}, {pending.action.y}{pending.action.type==='scroll'?` · ${pending.action.text}`:''}</code>}</div>{!['done','blocked'].includes(pending.action.type)&&<button className="primary-button" onClick={approve}>Allow this step</button>}<button className="icon-button" aria-label="Stop task" onClick={stop}><X size={18}/></button></>:<><CircleHelp size={18}/><p>{message}</p><button aria-label="Dismiss message" className="icon-button" onClick={()=>setMessage('')}><X size={16}/></button></>}</div>}
 {(voice.phase!=='idle'||voice.error)&&<div className="voice-task-status" role="status"><Volume2 size={15}/>{voice.error|| (voice.phase==='generating'?'Preparing Bebo’s voice…':'Bebo is speaking…')}{voice.phase!=='idle'&&<button className="text-button" onClick={voice.stop}>Stop voice</button>}</div>}
 <div className="section-title"><h2>A few things we can do</h2><span>Small asks. Big time-savers.</span></div><div className="quick-grid">{starterCommands.map(({title,prompt,desc,icon:Icon,color})=><button className="quick-card" key={title} onClick={()=>{setPrompt(prompt);promptRef.current?.focus();}}><span className={`quick-icon ${color}`}><Icon size={20}/></span><h3>{title}<ArrowRight size={16}/></h3><p>{desc}</p></button>)}</div><div className="bottom-note"><span><ShieldCheck size={14}/> {preferences.autoActions.length?'Automatic actions enabled. You can stop Bebo anytime.':'Your laptop. Your rules. Choose permissions in Settings.'}</span><button onClick={()=>setModal('help')}>How Bebo works <ArrowRight size={13}/></button></div></>:
 page==='Usage'?<UsagePage/>:page==='Activity'?<><WorkActivity/>{(!window.bebo?.workHistory||history.length>0)&&<section className="content-panel"><div className="section-title"><h2>Your activity</h2><button disabled={!history.length} onClick={()=>setHistory([])} className="text-button">Clear history</button></div>{history.length?history.map((entry,i)=><div className="activity-row" key={i}><span className={`activity-icon ${entry.ok?'green':'peach'}`}>{entry.ok?<Check size={20}/>:<CircleHelp size={20}/>}</span><div><h3>{entry.text}</h3><p>{entry.detail}</p></div><time>{new Date(entry.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>):<div className="empty-state"><Clock3 size={35}/><h2>A fresh little start.</h2><p>Completed requests and errors will show up here.<br/>Let’s make your first one happen.</p><button className="primary-button" onClick={()=>setPage('Home')}>Talk to Bebo <ArrowRight size={16}/></button></div>}</section>}</>:
 page==='Shortcuts'?<section className="content-panel"><div className="section-title"><h2>Your everyday little helpers</h2><button className="primary-button" onClick={()=>{setPrompt('');setModal('shortcut');}}><Plus size={16}/>New shortcut</button></div>{shortcuts.map((s,i)=><div className="activity-row" key={i}><span className="activity-icon lavender"><Zap size={19}/></span><div><h3>{s}</h3><p>Run when you need it</p></div><button className="icon-button" aria-label={`Run ${s}`} onClick={()=>{setPage('Home');void run(s);}}><Play size={18}/></button><button className="icon-button" aria-label={`Delete ${s}`} onClick={()=>setShortcuts(v=>v.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}</section>:
 page==='Phone'?<PhoneSetup color={color}/>:<><ExpressionStudio color={color} energy={energy} onEnergyChange={setEnergy}/><section className="personalize-panel avatar-options-panel"><div className="personalize-options"><div className="eyebrow">A SPLASH OF PERSONALITY</div><h2>Choose Bebo’s look</h2><p>The original OpenAgents editions, now at home with Bebo.</p><div className="swatches">{['ember','orbit','sprout','ink'].map(c=><button key={c} aria-label={`${c} edition`} title={c[0].toUpperCase()+c.slice(1)} aria-pressed={color===c} className={`swatch ${c}`} onClick={()=>setColor(c)}>{color===c&&<Check size={22}/>}</button>)}</div><div className="setting-row"><div><b>A voice of his own</b><p>Read completed responses aloud</p></div><button className={`toggle ${sound?'on':''}`} role="switch" aria-checked={sound} aria-label="Spoken responses" onClick={()=>setSound(!sound)}><span/></button></div><VoiceSettings voice={voice}/><CursorSettings color={color} calm={energy==='calm'}/><button className="primary-button" onClick={()=>window.bebo?window.bebo.pet():setModal('desktop')}><Monitor size={17}/>Bring Bebo to my desktop</button></div></section></>}
 <footer><span className="footer-brand">bebo.</span><span>Made for your everyday. And your someday.</span><span>Little friend, endless possibilities <span className="footer-flower">✳</span></span></footer></div></main>
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={modalRef}><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button><div className="modal-symbol"><Sparkles size={24}/></div><h2 id="modal-title">{modal==='connect'?'Give Bebo a little brain.':modal==='desktop'?'A friend on your desktop.':modal==='settings'?'Make yourself at home.':modal==='shortcut'?'A little shortcut.':'Small steps. You’re in control.'}</h2>
 {modal==='connect'?<><p>Bebo uses GPT-6 Luna to understand your request and choose the next action.</p>{window.bebo?<><label htmlFor="api-key">{connected?'Replace OpenAI API key':'OpenAI API key'}</label><input id="api-key" type="password" placeholder="sk-…" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/><p className="fine-print">Encrypted on this Windows account and remembered across restarts and Bebo updates. The saved key is never shown here or sent to your phone. When you send a request, Bebo sends your request and relevant tool results to OpenAI. These may include file contents, command output, app information, and screenshots when needed. Your permission settings decide which actions run automatically. Enhanced transcription also sends recorded audio to OpenAI.</p>{connectionStatus.saved&&<p className="fine-print">Your Luna key is saved on this device.</p>}{connectionStatus.error&&<p role="alert">{connectionStatus.error}</p>}<button disabled={!key.trim()||busy} className="primary-button full" onClick={connect}>{busy?'Checking connection…':connected?'Update saved key':'Connect Luna 6'}<ArrowRight size={16}/></button>{(connected||connectionStatus.error)&&window.bebo.forgetKey&&<button className="text-button" disabled={busy} onClick={()=>void forgetKey()}>Forget saved key and disconnect</button>}</>:<><div className="info-box"><Monitor size={20}/><div><b>Open the Windows app to connect</b><p>This browser preview cannot access your desktop or store your API key.</p></div></div><p>From the project folder, run:</p><code className="code-block">npm run desktop</code></>}{message&&<p role="alert">{message}</p>}</>:
 modal==='desktop'?<><p>Bebo can live in a little floating window, ready when you need him.</p><div className="info-box"><Monitor size={22}/><div><b>Windows desktop app</b><p>Run the command below from the Bebo project folder. Then choose “Meet desktop Bebo”.</p></div></div><code className="code-block">npm run desktop</code><p className="fine-print">Requires Windows, Node.js, and installed project dependencies. Desktop control requires an OpenAI API key.</p></>:
 modal==='settings'?<><div className="setting-row"><div><b>Luna 6 connection</b><p>{connectionStatus.error|| (connected?(connectionStatus.saved?'Saved securely · reconnects after restart':'Connected'):'Ready to connect in the desktop app')}</p></div><button className="text-button" onClick={()=>setModal('connect')}>{connected?'Update':'Connect'}<ChevronRight size={14}/></button></div><div className="setting-row"><div><b>Spoken responses</b><p>Hear Bebo’s completed responses</p></div><button className={`toggle ${sound?'on':''}`} role="switch" aria-checked={sound} aria-label="Spoken responses" onClick={()=>setSound(!sound)}><span/></button></div><div className="setting-row"><div><b>Appearance</b><p>Give Bebo a color of his own</p></div><button className="text-button" onClick={()=>{setPage('Personalize');setModal(null);}}>Personalize<ChevronRight size={14}/></button></div><AssistantSettings/><WorkSettings/><div className="info-box"><ShieldCheck size={21}/><p>Press Ctrl + Alt + Escape to stop Bebo, even outside the app.</p></div></>:
 modal==='shortcut'?<form onSubmit={e=>{e.preventDefault();if(prompt.trim()){setShortcuts(s=>[...s,prompt.trim()]);setModal(null);setPrompt('');}}}><label htmlFor="shortcut">What should Bebo do?</label><input id="shortcut" value={prompt} maxLength={500} onChange={e=>setPrompt(e.target.value)} placeholder="Open my favorite music app"/><button type="submit" disabled={!prompt.trim()} className="primary-button full">Save shortcut <Plus size={16}/></button></form>:
 <><p>Tell Bebo what you’d like to do. Luna chooses file tools, apps, the terminal, or the screen, then checks the result.</p><ol className="how-list"><li><Mic size={20}/><div><b>Say it, or type it.</b><p>Try “Open Chrome” or “Find my Downloads”.</p></div></li><li><MousePointer2 size={20}/><div><b>See the next step.</b><p>See each step in Activity. Review commands or file changes when your settings require it.</p></div></li><li><ShieldCheck size={20}/><div><b>Stay in the driver’s seat.</b><p>Stop at any time with Ctrl + Alt + Escape, including terminal work. Bebo refreshes the screen before each visual action.</p></div></li></ol><p className="fine-print">This is an early desktop assistant. It may make mistakes, cannot interact with Windows security prompts, and does not guarantee every task can be completed. Screenshots are sent only during requests.</p></>}
 </div></div>}
 </div></MotionConfig>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode>{new URLSearchParams(location.search).has('phone')?<PhoneController/>:new URLSearchParams(location.search).has('pet')?<DesktopPet/>:<App/>}</React.StrictMode>);
